# Generated by Django 4.1.5 on 2023-01-29 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Applicants",
            fields=[
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="applicant_images/default.jpg",
                        null=True,
                        upload_to="applicant_images",
                    ),
                ),
                (
                    "birthday",
                    models.DateField(blank=True, verbose_name="Дата рождения"),
                ),
                (
                    "phone",
                    models.CharField(max_length=20, verbose_name="Телефон соискателя"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Соискатель",
                "verbose_name_plural": "Соискатели",
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Навык"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание навыка"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Навык",
                "verbose_name_plural": "Навыки",
            },
        ),
        migrations.CreateModel(
            name="Towns",
            fields=[
                (
                    "town",
                    models.CharField(
                        db_index=True, max_length=50, unique=True, verbose_name="Город"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Город",
                "verbose_name_plural": "Города",
                "ordering": ("town",),
            },
        ),
        migrations.CreateModel(
            name="Resumes",
            fields=[
                (
                    "verification",
                    models.BooleanField(
                        default=False, verbose_name="Прохождение модерации"
                    ),
                ),
                (
                    "required_job",
                    models.TextField(
                        blank=True, null=True, verbose_name="Требуемая работа/должность"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="applicant_images/default.jpg",
                        null=True,
                        upload_to="applicant_images",
                        verbose_name="FOTO",
                    ),
                ),
                (
                    "salary",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Зарплата"
                    ),
                ),
                (
                    "last_job",
                    models.TextField(
                        blank=True, null=True, verbose_name="Последнее место работы"
                    ),
                ),
                (
                    "education",
                    models.TextField(
                        blank=True, null=True, verbose_name="Образование/курсы"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания резюме"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Опубликовать"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "applicants",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applicantapp.applicants",
                        verbose_name="Соискатель",
                    ),
                ),
                (
                    "skills",
                    models.ManyToManyField(
                        blank=True,
                        to="applicantapp.skill",
                        verbose_name="Ключевые навыки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Резюме",
                "verbose_name_plural": "Резюме",
            },
        ),
        migrations.AddField(
            model_name="applicants",
            name="town",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="applicantapp.towns",
                verbose_name="Город проживания",
            ),
        ),
        migrations.AddField(
            model_name="applicants",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
