# Generated by Django 4.1.5 on 2023-02-06 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employerapp", "0002_alter_vacancybody_options_and_more"),
        ("applicantapp", "0003_remove_skill_created_remove_skill_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Response",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cover_letter",
                    models.TextField(blank=True, verbose_name="Сопроводительное письмо"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "Новая"),
                            ("READ", "Просмотрено"),
                            ("ACCEPTED", "Принято"),
                            ("REJECTED", "Откланено"),
                        ],
                        default="NEW",
                        max_length=8,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата публикации"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "resume",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="applicantapp.resumes",
                        verbose_name="Резюме",
                    ),
                ),
                (
                    "vacancyheader",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="employerapp.vacancyheader",
                        verbose_name="Вакансии",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отклик",
                "verbose_name_plural": "Отклики",
            },
        ),
    ]
