# Generated by Django 4.1.5 on 2023-03-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supportapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="reason",
            field=models.SmallIntegerField(
                choices=[
                    (1, "Registration"),
                    (2, "Profile"),
                    (3, "Image Upload"),
                    (4, "Resume Response"),
                    (5, "Other"),
                ],
                default=1,
            ),
        ),
    ]
