# Generated by Django 4.1.5 on 2023-03-06 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("supportapp", "0003_rename_started_by_ticket_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={},
        ),
        migrations.AlterModelOptions(
            name="ticketmessage",
            options={"verbose_name": "Messages"},
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="active",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="reason",
        ),
        migrations.AddField(
            model_name="ticket",
            name="status",
            field=models.SmallIntegerField(
                choices=[(1, "active"), (2, "solved"), (3, "closed")], default=1
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="topic",
            field=models.SmallIntegerField(
                choices=[
                    (1, "Registration"),
                    (2, "Profile"),
                    (3, "Login"),
                    (4, "Account access"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="ticketmessage",
            name="message",
            field=models.CharField(max_length=255),
        ),
        migrations.RemoveField(
            model_name="ticketmessage",
            name="ticket",
        ),
        migrations.AlterField(
            model_name="ticketmessage",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ticketmessage",
            name="ticket",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="supportapp.ticket",
            ),
        ),
    ]
