# Generated by Django 4.1.5 on 2023-01-31 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="NewsSource"
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="NewsAuthor"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="NewsTitle")),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="NewsDescription"
                    ),
                ),
                (
                    "content",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="NewsContent",
                    ),
                ),
                ("url", models.URLField(blank=True, null=True, verbose_name="NewsUrl")),
                (
                    "image",
                    models.URLField(blank=True, null=True, verbose_name="NewsImageUrl"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 1, 31, 21, 32, 48, 610536),
                        verbose_name="NewsPublishedAt",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("deleted", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "News",
                "verbose_name_plural": "News",
                "ordering": ("-created",),
            },
        ),
    ]
