# Generated by Django 4.1.5 on 2023-02-01 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsapp", "0001_news_model_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="published_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 2, 1, 23, 0, 13, 157259),
                verbose_name="NewsPublishedAt",
            ),
        ),
    ]
