# Generated by Django 4.1.5 on 2023-02-01 20:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsapp", "0002_alter_news_published_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="published_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 2, 1, 23, 3, 18, 503443),
                verbose_name="NewsPublishedAt",
            ),
        ),
    ]
